### ISSUE TITLE
RFE: attach /tmp/anaconda* files for Anaconda crashes

### ISSUE THREAD

**Issue by jfilak** [rhinstaller/python-meh#3]
See abrt/abrt#999 for more details.

**Comment by dashea** [comment]
Uh, we do. python-meh is the one that creates the file in the first place.

Looking closer, the crash in https://bugzilla.redhat.com/1233177 happened early, before meh was initialized, so there would have been on anaconda-tb to attach, but abrt didn't even paste the traceback into the bug report. That's not very helpful!

**Comment by jfilak** [comment]
I apologize for confusion - I did not notice that the reporter ran Anaconda from the Fedora Live image and the exception has been caught by ABRT.
